### ISSUE TITLE
Configure TravisCI check in magic

### ISSUE THREAD

**Issue by jraviotta** [magic8bot/magic8bot#99]
Project administration #82

**Comment by Shawn8901** [comment]
@notVitaliy  will you create a travisCI account for magicbot8? 
I will create a pr for a travis configuration. it can be checked for a fork i have created for some testing for the travis config.
To cross check how it would look like:

https://travis-ci.org/Shawn8901/magic8bot
https://github.com/Shawn8901/magic8bot

Otherwise you could also grant me or maybe @jraviotta the rights then we could admin the travisCI stuff (if you are interested in).

On my travis build you can also see that there are 2 unit tests somehow flanky...

**Comment by Shawn8901** [comment]
@jraviotta  i think we can close this issue, because #116 was merged and now every commit is build by travisCI, what do you think?

**Comment by jraviotta** [comment]
Did the travisCI account get updated with the new organization? When that's working again, I agree that this issue can be closed. Thanks @Shawn8901

**Comment by Shawn8901** [comment]
Yup, it's now working again. https://travis-ci.com/magic8bot/magic8bot

**Comment by jraviotta** [comment]
Success!
